name: angular_dart_example
version: 0.0.1
dependencies:
  angular:
    path: ../
  browser: any
  unittest: any
  web_components: any

transformers:
- angular

# TODO(vicb): DI needs to be updated
# conflicting core pkgs: intl, code_transformers
dependency_overrides:
  analyzer: '0.15.7'
